### ISSUE TITLE
Ignore some routes?

### ISSUE THREAD

**Issue by steigerwald** [AOEpeople/Aoe_Profiler#29]
Thinking of using this a bit more but alot of noise from some routes being profiled.  Has anyone considered adding a setting so a user can define routes to ignore?

**Comment by fbrnc** [comment]
Hi Tom,
is this what you're asking for? 
https://github.com/AOEpeople/Aoe_Profiler/blob/master/var/aoe_profiler.xml.sample#L54-55

**Comment by steigerwald** [comment]
:+1: That is what I was looking for, didn't think to look in that portion.

**Comment by aftabnaveed** [comment]
I know this issue is closed, but I can't figure it out. I see the index.php/admin URL been blacklisted but it still logs the URls. When I look into the code in Aoe_Profiler_Model_Observer::persistProfile there is no reference to check to filter black listed or include white listed. May be I am missing something here?

**Comment by aftabnaveed** [comment]
Sorry me again :-) Varien_Profiler::enable()  was uncommented in index.php, commenting that fixed the issue.
